python_version = "3.13.12"
search-path = ["."]
project-includes = ["kuu"]

project-excludes = ["**/.[!/.]*", "**/tests"]
site-package-path = [
  ".venv/lib/python3.14/site-packages",
  ".venv/lib/python3.13/site-packages",
]
python-interpreter-path = ".venv/bin/python"
untyped-def-behavior = "check-and-infer-return-any"
ignore-errors-in-generated-code = true
disable-search-path-heuristics = true
