from typing import Any, Literal, Protocol, overload


class QSerializerProtocol(Protocol):
    def serialize(self, data: Any) -> bytes: ...

    @overload
    def deserialize[T](self, data: bytes, into: type[T]) -> T: ...
    @overload
    def deserialize[T](self, data: bytes, into: Literal[None] = None) -> object: ...

    def deserialize[T](self, data: bytes, into: type[T] | None = None) -> T | object: ...
